### ISSUE TITLE
请问您实现的这个LPN是否使用了论文中描述的那种训练方式训练的？还有如何在COCO test-dev上测试？

### ISSUE THREAD

**Issue by touhou-ayaya** [sailyung/human-pose-estimation#4]
- 请问您实现的这个LPN是否使用了论文中描述的那种训练方式训练的？

- 还有如何在COCO test-dev上测试？
> 我在网上搜索过，但这方面的说明很少，您对此比较了解的话，可以告知我吗？

**Comment by rhifbjbfdg** [comment]
> * 请问您实现的这个LPN是否使用了论文中描述的那种训练方式训练的？
> * 还有如何在COCO test-dev上测试？
> 
> > 我在网上搜索过，但这方面的说明很少，您对此比较了解的话，可以告知我吗？



> * 请问您实现的这个LPN是否使用了论文中描述的那种训练方式训练的？
> * 还有如何在COCO test-dev上测试？
> 
> > 我在网上搜索过，但这方面的说明很少，您对此比较了解的话，可以告知我吗？

第一个问题，不知道。
第二个问题，你可以按照这个网址的提示来操作
https://cocodataset.org/#upload

**Comment by touhou-ayaya** [comment]
> > * 请问您实现的这个LPN是否使用了论文中描述的那种训练方式训练的？
> > * 还有如何在COCO test-dev上测试？
> > 
> > > 我在网上搜索过，但这方面的说明很少，您对此比较了解的话，可以告知我吗？
> 
> > * 请问您实现的这个LPN是否使用了论文中描述的那种训练方式训练的？
> > * 还有如何在COCO test-dev上测试？
> > 
> > > 我在网上搜索过，但这方面的说明很少，您对此比较了解的话，可以告知我吗？
> 
> 第一个问题，不知道。
> 第二个问题，你可以按照这个网址的提示来操作
> https://cocodataset.org/#upload

好的，十分感谢:smile:

**Comment by sailyung** [comment]
只训练了第一轮，后边的也好操作按论文意思来,不过感觉很慢没试，我只是满足任务精度需求就没再弄,一轮大概半天2080，7轮少说也得5天那样

**Comment by touhou-ayaya** [comment]
感谢您的答复:smile:，我加载您训练的权重再反复训练了几次，发现除了**AP(L)** 与 **AR**，前面4个值都高于论文中的。从您的代码分析，我猜测可能是权重初始化导致的差异。

**Comment by sailyung** [comment]
你猜的对着，当时用simplebaseline代码直接修改的，我当时把那块初始化的代码删了，我看对AP没影响就删了

**Comment by sailyung** [comment]
如果方便，你可以把精度更高的模型上传下供大家使用
